# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
